(cd atmosphere-packages/webpack && meteor publish)
(cd atmosphere-packages/webpack-dev-middleware && meteor publish)
(cd examples/angular && meteor update --all-packages --allow-incompatible-update)
(cd examples/react && meteor update --all-packages --allow-incompatible-update)
(cd examples/vanilla && meteor update --all-packages --allow-incompatible-update)
(cd examples/vue && meteor update --all-packages --allow-incompatible-update)